### ISSUE TITLE
ECMH implementation based on this library

### ISSUE THREAD

**Issue by arj03** [paulmillr/noble-secp256k1#27]
Hi

I have been using this excellent library to implement the multiset hash using elliptic curves algorithm described in [ecmh.wiki](https://github.com/tomasvdw/bips/blob/master/ecmh.mediawiki). The implementation can be found here: https://github.com/arj03/ecmh-js. I'm using [Point.fromHex](https://github.com/arj03/ecmh-js/blob/911a84b9f94b23c41a01a03eba8a889dd4d565a9/index.js#L26) to figure out if point is on the curve. Sadly that function throws an exception which normally is rather slow. Do you have any input on a better way to do that part of the algorithm?

Cheers

PS: the post https://paulmillr.com/posts/noble-secp256k1-fast-ecc/ was very good in helping me implement this

**Comment by paulmillr** [comment]
The slowness of fromHex is not because it throws an exception. The real reason is the fact the point decompression is slow. To decompress a point, you need to exponentiate its x coordinate by curve order (x^(2^256-...)). As you can imagine this operation is extremely slow. 

If you want a speedup, you can use decompressed 65-byte points.

**Comment by arj03** [comment]
Thanks, that makes sense.
